services:
  app:
    build: .
    container_name: sameer
    command: uvicorn Sameer.main:app --host 0.0.0.0 --port 80 --reload --reload-include *
    ports:
      - 8000:80
    volumes:
      - .:/app
